// ============================================================
//  GEORGIA TRIPS — Tours Data Module
//  Each tour has a `category` field:
//    "one-day"   → One-Day Tours
//    "multi-day" → Multi-Day Tours
//    "flexible"  → Flexible Tours
//    "upcoming"  → Upcoming Tours (include dateRange + dateStart)
// ============================================================

const TOURS = [

  // ── ONE-DAY TOURS ──────────────────────────────────────────
  {
    id: 'od-1',
    category: 'one-day',
    title: 'Mtskheta & Jvari Monastery',
    price: '$49',
    duration: '1 Day',
    groupSize: 'Up to 10',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=700&q=80',
    desc: 'Visit Georgia\'s ancient capital Mtskheta and the iconic Jvari Church perched above the confluence of the Mtkvari and Aragvi rivers.',
    highlights: ['Svetitskhoveli Cathedral', 'Jvari Monastery', 'Shio-Mgvime Cave Monastery'],
    isFeatured: false,
  },
  {
    id: 'od-2',
    category: 'one-day',
    title: 'Kakheti Wine & Monastery Day',
    price: '$65',
    duration: '1 Day',
    groupSize: 'Up to 12',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=700&q=80',
    desc: 'Explore the cradle of wine civilization. Visit Alaverdi Monastery, taste Rkatsiteli and Saperavi in a family cellar, and wander Sighnaghi\'s cobblestone streets.',
    highlights: ['Alaverdi Monastery', 'Sighnaghi Old Town', 'Qvevri wine tasting'],
    isFeatured: false,
  },
  {
    id: 'od-3',
    category: 'one-day',
    title: 'Kazbegi Mountain Adventure',
    price: '$79',
    duration: '1 Day',
    groupSize: 'Up to 8',
    difficulty: 'Moderate',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&q=80',
    desc: 'Journey along the Georgian Military Highway to the breathtaking Kazbegi region. Hike to Gergeti Trinity Church at 2,170 m with panoramic Caucasus views.',
    highlights: ['Gergeti Trinity Church', 'Mount Kazbek views', 'Ananuri Fortress'],
    isFeatured: false,
  },
  {
    id: 'od-4',
    category: 'one-day',
    title: 'Tbilisi Hidden Gems Walk',
    price: '$35',
    duration: '1 Day',
    groupSize: 'Up to 15',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=700&q=80',
    desc: 'Dive deep into the layers of Old Tbilisi — sulfur baths, Persian-era caravanserais, colorful balconies and the best local street food spots.',
    highlights: ['Abanotubani Sulphur Baths', 'Narikala Fortress', 'Dry Bridge Market'],
    isFeatured: false,
  },

  // ── MULTI-DAY TOURS ────────────────────────────────────────
  {
    id: 'md-1',
    category: 'multi-day',
    title: 'Best of Georgia — 5 Days',
    price: '$420',
    duration: '5 Days',
    groupSize: 'Up to 8',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=700&q=80',
    desc: 'The perfect introduction to Georgia: Tbilisi, Mtskheta, Gori, Uplistsikhe cave city, Borjomi spa resort and the Surami Fortress. History at every turn.',
    highlights: ['Uplistsikhe Cave City', 'Borjomi Mineral Springs', 'Stalin Museum, Gori'],
    isFeatured: false,
  },
  {
    id: 'md-2',
    category: 'multi-day',
    title: 'Mountains & Black Sea — 7 Days',
    price: '$680',
    duration: '7 Days',
    groupSize: 'Up to 10',
    difficulty: 'Moderate',
    img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=700&q=80',
    desc: 'From the snowy peaks of Kazbegi to the subtropical beaches of Batumi — experience Georgia\'s full geographic and cultural range in one epic week.',
    highlights: ['Kazbegi Highlands', 'Kutaisi & Bagrati Cathedral', 'Batumi Boulevard'],
    isFeatured: false,
  },
  {
    id: 'md-3',
    category: 'multi-day',
    title: 'Hidden Georgia — 10 Days',
    price: '$990',
    duration: '10 Days',
    groupSize: 'Up to 6',
    difficulty: 'Challenging',
    img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80',
    desc: 'Off-the-beaten-path villages, medieval Svaneti towers, Mestia, Ushguli — the highest inhabited village in Europe — and remote Tusheti gorges.',
    highlights: ['Ushguli Village (UNESCO)', 'Mestia Tower Houses', 'Tusheti Road'],
    isFeatured: false,
  },
  {
    id: 'md-4',
    category: 'multi-day',
    title: 'Wine & Culture — 4 Days',
    price: '$320',
    duration: '4 Days',
    groupSize: 'Up to 10',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=700&q=80',
    desc: 'A four-day deep dive into Georgian wine culture: Kakheti\'s qvevri cellars, Telavi old town, Gremi Castle and a stay in a family guesthouse among vineyards.',
    highlights: ['Telavi Old Town', 'Gremi Fortress', 'Qvevri wine making'],
    isFeatured: false,
  },

  // ── FLEXIBLE TOURS ─────────────────────────────────────────
  {
    id: 'fl-1',
    category: 'flexible',
    title: 'Private Tbilisi at Your Pace',
    price: 'From $85',
    duration: 'Flexible',
    groupSize: '1–8 People',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=700&q=80',
    desc: 'Design your own Tbilisi day. Choose your start time, your sites and your pace. A private guide adapts entirely to your interests — art, history, food or all three.',
    highlights: ['Fully customizable itinerary', 'Private licensed guide', 'Hotel pickup included'],
    isFeatured: false,
  },
  {
    id: 'fl-2',
    category: 'flexible',
    title: 'School Excursion Package',
    price: 'From $25/student',
    duration: '1–5 Days',
    groupSize: '10–50 Students',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=700&q=80',
    desc: 'Educational tours tailored for school groups — curriculum-linked content, safe transport, bilingual guides and flexible multi-day options. Prices on request.',
    highlights: ['Curriculum-linked content', 'Supervised at all times', 'Budget-friendly rates'],
    isFeatured: false,
  },
  {
    id: 'fl-3',
    category: 'flexible',
    title: 'Honeymoon & Romantic Getaway',
    price: 'From $199/couple',
    duration: 'Flexible',
    groupSize: '2 People',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=700&q=80',
    desc: 'A curated romantic journey through Georgia — boutique guesthouses, candlelit dinners, private wine tastings and sunset views over the Caucasus.',
    highlights: ['Boutique accommodations', 'Private experiences only', 'Fully personalized'],
    isFeatured: false,
  },
  {
    id: 'fl-4',
    category: 'flexible',
    title: 'Photography Tour — Any Route',
    price: 'From $95',
    duration: 'Flexible',
    groupSize: '1–4 People',
    difficulty: 'Easy–Moderate',
    img: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=700&q=80',
    desc: 'Built for photographers. We time routes around golden hour, access restricted viewpoints, and move at a slow deliberate pace wherever the light takes you.',
    highlights: ['Golden hour scheduling', 'Hidden viewpoints', 'Any destination'],
    isFeatured: false,
  },

  // ── UPCOMING TOURS ─────────────────────────────────────────
  {
    id: 'up-1',
    category: 'upcoming',
    title: 'Svaneti Trekking Expedition',
    price: '$580',
    duration: '6 Days',
    groupSize: 'Up to 8',
    difficulty: 'Challenging',
    img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80',
    desc: 'Trek through the remote Svaneti highlands — medieval tower villages, glacial lakes and ridgeline views that feel like the edge of the world.',
    highlights: ['Chalaadi Glacier', 'Koruldi Lakes', 'Ushguli Village'],
    dateRange: 'June 10 – 15, 2025',
    dateStart: '2025-06-10',
    spotsLeft: 3,
    isFeatured: false,
  },
  {
    id: 'up-2',
    category: 'upcoming',
    title: 'Kakheti Harvest Festival Tour',
    price: '$290',
    duration: '3 Days',
    groupSize: 'Up to 12',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=700&q=80',
    desc: 'Join the Rtveli — Georgia\'s ancient grape harvest. Stomp grapes, fill qvevri vessels and feast with a winemaking family in the Alazani Valley.',
    highlights: ['Grape harvest participation', 'Qvevri wine filling', 'Family feast'],
    dateRange: 'June 20 – 22, 2025',
    dateStart: '2025-06-20',
    spotsLeft: 7,
    isFeatured: false,
  },
  {
    id: 'up-3',
    category: 'upcoming',
    title: 'Kazbegi Midsummer Trek',
    price: '$195',
    duration: '2 Days',
    groupSize: 'Up to 10',
    difficulty: 'Moderate',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&q=80',
    desc: 'An overnight mountain escape to Kazbegi during the long midsummer days — hike to Gergeti, camp under the Milky Way, and return with memories for life.',
    highlights: ['Overnight mountain camp', 'Gergeti at sunrise', 'Glacier viewpoint'],
    dateRange: 'July 4 – 5, 2025',
    dateStart: '2025-07-04',
    spotsLeft: 5,
    isFeatured: false,
  },
  {
    id: 'up-4',
    category: 'upcoming',
    title: 'Tbilisi Open City Weekend',
    price: '$120',
    duration: '2 Days',
    groupSize: 'Up to 15',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=700&q=80',
    desc: 'A curated weekend experience timed with Tbilisi\'s Open City festival — architecture walks, pop-up galleries, rooftop dinners and live Georgian polyphony.',
    highlights: ['Architecture walking tour', 'Rooftop dinner', 'Live polyphonic choir'],
    dateRange: 'July 18 – 19, 2025',
    dateStart: '2025-07-18',
    spotsLeft: 10,
    isFeatured: false,
  },
  {
    id: 'up-5',
    category: 'upcoming',
    title: 'Batumi Summer Escape',
    price: '$345',
    duration: '4 Days',
    groupSize: 'Up to 12',
    difficulty: 'Easy',
    img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=700&q=80',
    desc: 'The Black Sea at its finest — Batumi\'s art nouveau boulevard, Adjara botanical gardens, sea kayaking and day trips to Gonio-Apsaros fortress.',
    highlights: ['Batumi Botanical Garden', 'Sea Kayaking', 'Gonio-Apsaros Fortress'],
    dateRange: 'Aug 1 – 4, 2025',
    dateStart: '2025-08-01',
    spotsLeft: 8,
    isFeatured: false,
  },
];

// Export for use in other modules (also available as global for non-module scripts)
if (typeof module !== 'undefined') module.exports = { TOURS };
